#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 11 00:03:41 2020

@author: alfiantjandra
"""

from openpyxl import load_workbook

workbook=load_workbook(filename="fall_2016.xlsx")

sheet = workbook.active

total_dict = {"General Education":0}
name_tracker = "General Education"
total_courses = 0

for value in sheet.iter_rows(min_row=2,max_row=10000,min_col=1,max_col=14,values_only=True):
    if value[0] == "Grand Total":
        break
    else: 
        total_courses += 1
        

for value in sheet.iter_rows(min_row=2,max_row=total_courses,min_col=1,max_col=14,values_only=True):
    if value[4] == name_tracker:
        total_dict[value[4]] += value[13]
    else:
        name_tracker = value[4]
        total_dict[value[4]] = value[13]
        
print(total_dict)